# Generated by Django 2.1.7 on 2019-02-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Surveyquestion')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Surviver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.SurveyOption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Surveyquestion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='surviver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Surviver'),
        ),
    ]
