# Generated by Django 2.1.7 on 2019-02-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0003_auto_20190223_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoption',
            name='option_type',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='surveyoption',
            name='deneme',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Surveyquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyoption',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('O', 'Option')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
