# Generated by Django 2.1.7 on 2019-03-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0005_auto_20190224_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='surveyid',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='surveyExample.Surveyquestion'),
        ),
        migrations.DeleteModel(
            name='SurveyOption',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyExample.Surveyquestion'),
        ),
    ]
