# Generated by Django 2.1.7 on 2019-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0006_auto_20190305_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ManyToManyField(to='surveyExample.Survey'),
        ),
    ]
