# Generated by Django 2.1.7 on 2019-03-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0007_auto_20190305_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_image',
            field=models.ImageField(default='pic_survey/None/no-img.jpg', upload_to='pic_survey/'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_image',
            field=models.ImageField(default='pic_question/None/no-img.jpg', upload_to='pic_question/'),
        ),
    ]
