# Generated by Django 2.1.7 on 2019-03-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0009_auto_20190318_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question_image',
        ),
    ]
