# Generated by Django 2.1.7 on 2019-03-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0010_remove_surveyquestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
