# Generated by Django 2.1.7 on 2019-03-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyExample', '0011_surveyquestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
